export type Brand =
  | 'Midea'
  | 'Gree'
  | 'Yamato'
  | 'Fujitsu'
  | 'Yukon'
  | 'Habitat'
  | 'Bosch'
  | 'Vaillant'
  | 'Immergas'
  | 'Viessmann'
  | 'Generic'
  | 'PRO TERM';

export type Category =
  | 'aer-conditionat'
  | 'centrale-termice'
  | 'pompe-caldura'
  | 'accesorii-montaj-ac'
  | 'teava-fitinguri'
  | 'condens-drenaj'
  | 'termostate-automatizari'
  | 'service-montaj';

export type StockStatus = 'in-stock' | 'low-stock' | 'out-of-stock' | 'on-request';

export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  brand: Brand;
  category: Category;
  btu?: number;
  capacityLabel?: string;
  price: number;
  priceLabel?: string;
  originalPrice?: number;
  rating: number;
  reviews: number;
  isNew?: boolean;
  isBestseller?: boolean;
  energyClass: string;
  description: string;
  features: string[];
  specs: ProductSpec[];
  smartbillCode?: string;
  manageStock?: boolean;
  stockStatus?: StockStatus;
  stockQty?: number;
}

export const BRAND_GRADIENT: Record<Brand, string> = {
  Midea: 'from-red-600 to-rose-500',
  Gree: 'from-emerald-600 to-green-500',
  Yamato: 'from-orange-600 to-amber-500',
  Fujitsu: 'from-slate-700 to-slate-500',
  Yukon: 'from-sky-700 to-cyan-500',
  Habitat: 'from-lime-700 to-green-500',
  Bosch: 'from-red-700 to-neutral-700',
  Vaillant: 'from-green-700 to-emerald-500',
  Immergas: 'from-rose-700 to-red-500',
  Viessmann: 'from-neutral-800 to-red-600',
  Generic: 'from-gray-600 to-gray-400',
  'PRO TERM': 'from-primary to-accent',
};

export const CATEGORY_LABEL: Record<Category, string> = {
  'aer-conditionat': 'Aer condiționat',
  'centrale-termice': 'Centrale termice',
  'pompe-caldura': 'Pompe de căldură',
  'accesorii-montaj-ac': 'Accesorii montaj AC',
  'teava-fitinguri': 'Țeavă și fitinguri',
  'condens-drenaj': 'Condens și drenaj',
  'termostate-automatizari': 'Termostate & automatizări',
  'service-montaj': 'Service & montaj',
};

export const STOCK_LABEL: Record<StockStatus, string> = {
  'in-stock': 'În stoc',
  'low-stock': 'Stoc limitat',
  'out-of-stock': 'Indisponibil',
  'on-request': 'La cerere',
};

export const products: Product[] = [
  {
    id: "gree-fairy-a1-lclh-9000",
    slug: "gree-fairy-a1-lclh-9000-btu-gwh09acc-k6dna1f",
    name: "Gree Fairy A1 LCLH 9k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 9000,
    capacityLabel: "9.000 BTU",
    price: 2179,
    rating: 4.7,
    reviews: 9,
    energyClass: "A++",
    smartbillCode: "GWH09ACC-K6DNA1F",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Fairy A1 LCLH, model GWH09ACC-K6DNA1F. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH09ACC-K6DNA1F" },
      { label: "Serie", value: "Fairy A1 LCLH" },
      { label: "Capacitate", value: "9.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-fairy-a1-lclh-12000",
    slug: "gree-fairy-a1-lclh-12000-btu-gwh12acc-k6dna1f",
    name: "Gree Fairy A1 LCLH 12k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 2310,
    rating: 4.7,
    reviews: 10,
    energyClass: "A++",
    smartbillCode: "GWH12ACC-K6DNA1F",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Fairy A1 LCLH, model GWH12ACC-K6DNA1F. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH12ACC-K6DNA1F" },
      { label: "Serie", value: "Fairy A1 LCLH" },
      { label: "Capacitate", value: "12.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-fairy-a1-lclh-18000",
    slug: "gree-fairy-a1-lclh-18000-btu-gwh18acd-k6dna1i",
    name: "Gree Fairy A1 LCLH 18k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18.000 BTU",
    price: 3534,
    rating: 4.7,
    reviews: 11,
    energyClass: "A++",
    smartbillCode: "GWH18ACD-K6DNA1I",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Fairy A1 LCLH, model GWH18ACD-K6DNA1I. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH18ACD-K6DNA1I" },
      { label: "Serie", value: "Fairy A1 LCLH" },
      { label: "Capacitate", value: "18.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-fairy-a1-lclh-24000",
    slug: "gree-fairy-a1-lclh-24000-btu-gwh24ace-k6dna1i",
    name: "Gree Fairy A1 LCLH 24k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24.000 BTU",
    price: 4541,
    rating: 4.7,
    reviews: 12,
    energyClass: "A++",
    smartbillCode: "GWH24ACE-K6DNA1I",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Fairy A1 LCLH, model GWH24ACE-K6DNA1I. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH24ACE-K6DNA1I" },
      { label: "Serie", value: "Fairy A1 LCLH" },
      { label: "Capacitate", value: "24.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-pulsar-9000",
    slug: "gree-pulsar-9000-btu-gwh09agaxb-k6dna1b",
    name: "Gree Pulsar 9k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 9000,
    capacityLabel: "9.000 BTU",
    price: 1690,
    rating: 4.7,
    reviews: 13,
    isBestseller: true,
    energyClass: "A++",
    smartbillCode: "GWH09AGAXB-K6DNA1B",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Pulsar, model GWH09AGAXB-K6DNA1B. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH09AGAXB-K6DNA1B" },
      { label: "Serie", value: "Pulsar" },
      { label: "Capacitate", value: "9.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-pulsar-12000",
    slug: "gree-pulsar-12000-btu-gwh12agbxb-k6dna1a",
    name: "Gree Pulsar 12k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 1863,
    rating: 4.7,
    reviews: 14,
    isBestseller: true,
    energyClass: "A++",
    smartbillCode: "GWH12AGBXB-K6DNA1A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Pulsar, model GWH12AGBXB-K6DNA1A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH12AGBXB-K6DNA1A" },
      { label: "Serie", value: "Pulsar" },
      { label: "Capacitate", value: "12.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-pulsar-18000",
    slug: "gree-pulsar-18000-btu-gwh18agd-k6dna1d",
    name: "Gree Pulsar 18k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18.000 BTU",
    price: 3297,
    rating: 4.7,
    reviews: 15,
    energyClass: "A++",
    smartbillCode: "GWH18AGD-K6DNA1D",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Pulsar, model GWH18AGD-K6DNA1D. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH18AGD-K6DNA1D" },
      { label: "Serie", value: "Pulsar" },
      { label: "Capacitate", value: "18.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-pulsar-24000",
    slug: "gree-pulsar-24000-btu-gwh24agd-k6dna1c",
    name: "Gree Pulsar 24k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24.000 BTU",
    price: 4147,
    rating: 4.7,
    reviews: 16,
    energyClass: "A++",
    smartbillCode: "GWH24AGD-K6DNA1C",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Pulsar, model GWH24AGD-K6DNA1C. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH24AGD-K6DNA1C" },
      { label: "Serie", value: "Pulsar" },
      { label: "Capacitate", value: "24.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-bora-a4-silver-9000",
    slug: "gree-bora-a4-silver-9000-btu-gwh09aaaxb-k6dna4b",
    name: "Gree Bora A4 Silver 9k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 9000,
    capacityLabel: "9.000 BTU",
    price: 1688,
    rating: 4.7,
    reviews: 17,
    isBestseller: true,
    energyClass: "A++",
    smartbillCode: "GWH09AAAXB-K6DNA4B",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Bora A4 Silver, model GWH09AAAXB-K6DNA4B. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH09AAAXB-K6DNA4B" },
      { label: "Serie", value: "Bora A4 Silver" },
      { label: "Capacitate", value: "9.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-bora-a4-silver-12000",
    slug: "gree-bora-a4-silver-12000-btu-gwh12aabxb-k6dna4a",
    name: "Gree Bora A4 Silver 12k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 1861,
    rating: 4.7,
    reviews: 18,
    isBestseller: true,
    energyClass: "A++",
    smartbillCode: "GWH12AABXB-K6DNA4A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Bora A4 Silver, model GWH12AABXB-K6DNA4A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH12AABXB-K6DNA4A" },
      { label: "Serie", value: "Bora A4 Silver" },
      { label: "Capacitate", value: "12.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-bora-a4-silver-18000",
    slug: "gree-bora-a4-silver-18000-btu-gwh18aad-k6dna4e",
    name: "Gree Bora A4 Silver 18k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18.000 BTU",
    price: 3438,
    rating: 4.7,
    reviews: 19,
    energyClass: "A++",
    smartbillCode: "GWH18AAD-K6DNA4E",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Bora A4 Silver, model GWH18AAD-K6DNA4E. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH18AAD-K6DNA4E" },
      { label: "Serie", value: "Bora A4 Silver" },
      { label: "Capacitate", value: "18.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-bora-a4-silver-24000",
    slug: "gree-bora-a4-silver-24000-btu-gwh24aad-k6dna4b",
    name: "Gree Bora A4 Silver 24k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24.000 BTU",
    price: 4325,
    rating: 4.7,
    reviews: 20,
    energyClass: "A++",
    smartbillCode: "GWH24AAD-K6DNA4B",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree Bora A4 Silver, model GWH24AAD-K6DNA4B. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH24AAD-K6DNA4B" },
      { label: "Serie", value: "Bora A4 Silver" },
      { label: "Capacitate", value: "24.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-clivia-lclh-9000",
    slug: "gree-clivia-lclh-9000-btu-gwh09aucxb-k6dna1a",
    name: "Gree CLIVIA LCLH 9k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 9000,
    capacityLabel: "9.000 BTU",
    price: 2176,
    rating: 4.7,
    reviews: 21,
    energyClass: "A++",
    smartbillCode: "GWH09AUCXB-K6DNA1A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree CLIVIA LCLH, model GWH09AUCXB-K6DNA1A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH09AUCXB-K6DNA1A" },
      { label: "Serie", value: "CLIVIA LCLH" },
      { label: "Capacitate", value: "9.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-clivia-lclh-12000",
    slug: "gree-clivia-lclh-12000-btu-gwh12aucxd-k6dna1c",
    name: "Gree CLIVIA LCLH 12k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 2330,
    rating: 4.7,
    reviews: 22,
    energyClass: "A++",
    smartbillCode: "GWH12AUCXD-K6DNA1C",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree CLIVIA LCLH, model GWH12AUCXD-K6DNA1C. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH12AUCXD-K6DNA1C" },
      { label: "Serie", value: "CLIVIA LCLH" },
      { label: "Capacitate", value: "12.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-clivia-lclh-18000",
    slug: "gree-clivia-lclh-18000-btu-gwh18audxe-k6dna1a",
    name: "Gree CLIVIA LCLH 18k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18.000 BTU",
    price: 3287,
    rating: 4.7,
    reviews: 23,
    energyClass: "A++",
    smartbillCode: "GWH18AUDXE-K6DNA1A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree CLIVIA LCLH, model GWH18AUDXE-K6DNA1A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH18AUDXE-K6DNA1A" },
      { label: "Serie", value: "CLIVIA LCLH" },
      { label: "Capacitate", value: "18.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-clivia-lclh-24000",
    slug: "gree-clivia-lclh-24000-btu-gwh24audxf-k6dna1a",
    name: "Gree CLIVIA LCLH 24k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24.000 BTU",
    price: 4015,
    rating: 4.7,
    reviews: 24,
    energyClass: "A++",
    smartbillCode: "GWH24AUDXF-K6DNA1A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree CLIVIA LCLH, model GWH24AUDXF-K6DNA1A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH24AUDXF-K6DNA1A" },
      { label: "Serie", value: "CLIVIA LCLH" },
      { label: "Capacitate", value: "24.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-soyal-lclh-9000",
    slug: "gree-soyal-lclh-9000-btu-gwh09akcxd-k6dna1a",
    name: "Gree SOYAL LCLH 9k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 9000,
    capacityLabel: "9.000 BTU",
    price: 3892,
    rating: 4.8,
    reviews: 25,
    energyClass: "A++",
    smartbillCode: "GWH09AKCXD-K6DNA1A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree SOYAL LCLH, model GWH09AKCXD-K6DNA1A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH09AKCXD-K6DNA1A" },
      { label: "Serie", value: "SOYAL LCLH" },
      { label: "Capacitate", value: "9.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-soyal-lclh-12000",
    slug: "gree-soyal-lclh-12000-btu-gwh12akcxd-k6dna1a",
    name: "Gree SOYAL LCLH 12k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 4096,
    rating: 4.8,
    reviews: 26,
    energyClass: "A++",
    smartbillCode: "GWH12AKCXD-K6DNA1A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree SOYAL LCLH, model GWH12AKCXD-K6DNA1A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "GWH12AKCXD-K6DNA1A" },
      { label: "Serie", value: "SOYAL LCLH" },
      { label: "Capacitate", value: "12.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "gree-soyal-lclh-18000",
    slug: "gree-soyal-lclh-18000-btu-gwh18akcxf-k6dna1a",
    name: "Gree SOYAL LCLH 18k BTU",
    brand: "Gree",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18.000 BTU",
    price: 4567,
    rating: 4.8,
    reviews: 27,
    energyClass: "A++",
    smartbillCode: "GWH18AKCXF-K6DNA1A",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Gree SOYAL LCLH, model GWH18AKCXF-K6DNA1A. Preț calculat din coloana albă 10 bucăți, cu adaos 20%.",
    features: ["DC Inverter", "R32", "Montaj disponibil în Arad", "Ofertă cu accesorii și kit montaj"],
    specs: [
      { label: "Model furnizor", value: "GWH18AKCXF-K6DNA1A" },
      { label: "Serie", value: "SOYAL LCLH" },
      { label: "Capacitate", value: "18.000 BTU" },
      { label: "Preț calculat", value: "10 bucăți - coloana albă + adaos 20%" },
      { label: "TVA / timbru verde", value: "De verificat la facturare, conform listei furnizorului" },
    ],
  },
  {
    id: "yamato-yw09t2n",
    slug: "yamato-yw09t2n",
    name: "Yamato YW09T2n 9000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 9000,
    capacityLabel: "9000 BTU",
    price: 1429,
    rating: 4.6,
    reviews: 7,
    isNew: true,
    energyClass: "A++",
    smartbillCode: "YW09T2n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato OPTIMUM, categoria Wall mounted, model YW09T2n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW09T2n" },
      { label: "Serie / gamă", value: "OPTIMUM" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "9000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yw12t2n",
    slug: "yamato-yw12t2n",
    name: "Yamato YW12T2n 12000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12000 BTU",
    price: 1522,
    rating: 4.6,
    reviews: 8,
    energyClass: "A++",
    smartbillCode: "YW12T2n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato OPTIMUM, categoria Wall mounted, model YW12T2n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW12T2n" },
      { label: "Serie / gamă", value: "OPTIMUM" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "12000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yw18t2n",
    slug: "yamato-yw18t2n",
    name: "Yamato YW18T2n 18000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18000 BTU",
    price: 2526,
    rating: 4.6,
    reviews: 9,
    energyClass: "A++",
    smartbillCode: "YW18T2n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato OPTIMUM, categoria Wall mounted, model YW18T2n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW18T2n" },
      { label: "Serie / gamă", value: "OPTIMUM" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "18000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,5" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yw24t2n",
    slug: "yamato-yw24t2n",
    name: "Yamato YW24T2n 24000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24000 BTU",
    price: 3484,
    rating: 4.6,
    reviews: 10,
    energyClass: "A++",
    smartbillCode: "YW24T2n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato OPTIMUM, categoria Wall mounted, model YW24T2n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW24T2n" },
      { label: "Serie / gamă", value: "OPTIMUM" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "24000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,5" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yw09t3n",
    slug: "yamato-yw09t3n",
    name: "Yamato YW09T3n 9000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 9000,
    capacityLabel: "9000 BTU",
    price: 1548,
    rating: 4.6,
    reviews: 11,
    isNew: true,
    energyClass: "A++",
    smartbillCode: "YW09T3n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato AVANTI, categoria Wall mounted, model YW09T3n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW09T3n" },
      { label: "Serie / gamă", value: "AVANTI" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "9000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yw12t3n",
    slug: "yamato-yw12t3n",
    name: "Yamato YW12T3n 12000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12000 BTU",
    price: 1644,
    rating: 4.6,
    reviews: 12,
    energyClass: "A++",
    smartbillCode: "YW12T3n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato AVANTI, categoria Wall mounted, model YW12T3n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW12T3n" },
      { label: "Serie / gamă", value: "AVANTI" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "12000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yw18t3n",
    slug: "yamato-yw18t3n",
    name: "Yamato YW18T3n 18000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18000 BTU",
    price: 2652,
    rating: 4.6,
    reviews: 13,
    energyClass: "A++",
    smartbillCode: "YW18T3n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato AVANTI, categoria Wall mounted, model YW18T3n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW18T3n" },
      { label: "Serie / gamă", value: "AVANTI" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "18000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,5" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yw24t3n",
    slug: "yamato-yw24t3n",
    name: "Yamato YW24T3n 24000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24000 BTU",
    price: 3708,
    rating: 4.6,
    reviews: 14,
    energyClass: "A++",
    smartbillCode: "YW24T3n",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato AVANTI, categoria Wall mounted, model YW24T3n. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Control Wi-Fi", "Golden Fin UI + UE", "Kit instalare inclus"],
    specs: [
      { label: "Model furnizor", value: "YW24T3n" },
      { label: "Serie / gamă", value: "AVANTI" },
      { label: "Categorie", value: "Wall mounted" },
      { label: "Capacitate", value: "24000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,5" },
      { label: "Eficiență încălzire", value: "A+/4,1" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yc12t2",
    slug: "yamato-yc12t2",
    name: "Yamato YC12T2 12000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12000 BTU",
    price: 4228,
    rating: 4.5,
    reviews: 15,
    isNew: true,
    energyClass: "A++",
    smartbillCode: "YC12T2",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Caseta compacta, categoria Caseta compacta de tavan, model YC12T2. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Wi-Fi Ready", "Refulare circulară", "Telecomandă fără fir inclusă"],
    specs: [
      { label: "Model furnizor", value: "YC12T2" },
      { label: "Serie / gamă", value: "LCAC Caseta compacta" },
      { label: "Categorie", value: "Caseta compacta de tavan" },
      { label: "Capacitate", value: "12000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,5" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yc18t2",
    slug: "yamato-yc18t2",
    name: "Yamato YC18T2 16000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 16000,
    capacityLabel: "16000 BTU",
    price: 4392,
    rating: 4.5,
    reviews: 16,
    energyClass: "A++",
    smartbillCode: "YC18T2",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Caseta compacta, categoria Caseta compacta de tavan, model YC18T2. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Wi-Fi Ready", "Refulare circulară", "Telecomandă fără fir inclusă"],
    specs: [
      { label: "Model furnizor", value: "YC18T2" },
      { label: "Serie / gamă", value: "LCAC Caseta compacta" },
      { label: "Categorie", value: "Caseta compacta de tavan" },
      { label: "Capacitate", value: "16000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yc24t2",
    slug: "yamato-yc24t2",
    name: "Yamato YC24T2 24000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24000 BTU",
    price: 5200,
    rating: 4.5,
    reviews: 17,
    energyClass: "A++",
    smartbillCode: "YC24T2",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Caseta de tavan, categoria Caseta de tavan, model YC24T2. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Wi-Fi Ready", "Refulare circulară", "Telecomandă fără fir inclusă"],
    specs: [
      { label: "Model furnizor", value: "YC24T2" },
      { label: "Serie / gamă", value: "LCAC Caseta de tavan" },
      { label: "Categorie", value: "Caseta de tavan" },
      { label: "Capacitate", value: "24000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,2" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yc42t2",
    slug: "yamato-yc42t2",
    name: "Yamato YC42T2 42000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 42000,
    capacityLabel: "42000 BTU",
    price: 7728,
    rating: 4.5,
    reviews: 18,
    energyClass: "A++",
    smartbillCode: "YC42T2",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Caseta de tavan, categoria Caseta de tavan, model YC42T2. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Wi-Fi Ready", "Refulare circulară", "Telecomandă fără fir inclusă"],
    specs: [
      { label: "Model furnizor", value: "YC42T2" },
      { label: "Serie / gamă", value: "LCAC Caseta de tavan" },
      { label: "Categorie", value: "Caseta de tavan" },
      { label: "Capacitate", value: "42000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yc48t2t-trifazat",
    slug: "yamato-yc48t2t-trifazat",
    name: "Yamato YC48T2T trifazat 48000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 48000,
    capacityLabel: "48000 BTU",
    price: 9042,
    rating: 4.5,
    reviews: 19,
    energyClass: "A++",
    smartbillCode: "YC48T2T-trifazat",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Caseta de tavan, categoria Caseta de tavan, model YC48T2T trifazat. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Wi-Fi Ready", "Refulare circulară", "Telecomandă fără fir inclusă"],
    specs: [
      { label: "Model furnizor", value: "YC48T2T trifazat" },
      { label: "Serie / gamă", value: "LCAC Caseta de tavan" },
      { label: "Categorie", value: "Caseta de tavan" },
      { label: "Capacitate", value: "48000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yc55t2t-trifazat",
    slug: "yamato-yc55t2t-trifazat",
    name: "Yamato YC55T2T trifazat 55000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 55000,
    capacityLabel: "55000 BTU",
    price: 9895,
    rating: 4.5,
    reviews: 20,
    energyClass: "A++",
    smartbillCode: "YC55T2T-trifazat",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Caseta de tavan, categoria Caseta de tavan, model YC55T2T trifazat. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Wi-Fi Ready", "Refulare circulară", "Telecomandă fără fir inclusă"],
    specs: [
      { label: "Model furnizor", value: "YC55T2T trifazat" },
      { label: "Serie / gamă", value: "LCAC Caseta de tavan" },
      { label: "Categorie", value: "Caseta de tavan" },
      { label: "Capacitate", value: "55000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yd12t1",
    slug: "yamato-yd12t1",
    name: "Yamato YD12T1 12500 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 12500,
    capacityLabel: "12500 BTU",
    price: 4136,
    rating: 4.5,
    reviews: 21,
    energyClass: "A++",
    smartbillCode: "YD12T1",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Duct, categoria Duct, model YD12T1. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Presiune statică medie", "Telecomandă cu fir inclusă", "Fără pompă de condens"],
    specs: [
      { label: "Model furnizor", value: "YD12T1" },
      { label: "Serie / gamă", value: "LCAC Duct" },
      { label: "Categorie", value: "Duct" },
      { label: "Capacitate", value: "12500 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yd18t1",
    slug: "yamato-yd18t1",
    name: "Yamato YD18T1 18000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 18000,
    capacityLabel: "18000 BTU",
    price: 4242,
    rating: 4.5,
    reviews: 22,
    energyClass: "A++",
    smartbillCode: "YD18T1",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Duct, categoria Duct, model YD18T1. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Presiune statică medie", "Telecomandă cu fir inclusă", "Fără pompă de condens"],
    specs: [
      { label: "Model furnizor", value: "YD18T1" },
      { label: "Serie / gamă", value: "LCAC Duct" },
      { label: "Categorie", value: "Duct" },
      { label: "Capacitate", value: "18000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,3" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yd24t1",
    slug: "yamato-yd24t1",
    name: "Yamato YD24T1 24000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24000 BTU",
    price: 4908,
    rating: 4.5,
    reviews: 23,
    energyClass: "A++",
    smartbillCode: "YD24T1",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Duct, categoria Duct, model YD24T1. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Presiune statică medie", "Telecomandă cu fir inclusă", "Fără pompă de condens"],
    specs: [
      { label: "Model furnizor", value: "YD24T1" },
      { label: "Serie / gamă", value: "LCAC Duct" },
      { label: "Categorie", value: "Duct" },
      { label: "Capacitate", value: "24000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,2" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yd24t2",
    slug: "yamato-yd24t2",
    name: "Yamato YD24T2 24000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 24000,
    capacityLabel: "24000 BTU",
    price: 5172,
    rating: 4.5,
    reviews: 24,
    energyClass: "A++",
    smartbillCode: "YD24T2",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Duct, categoria Duct, model YD24T2. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Presiune statică medie", "Telecomandă cu fir inclusă", "Fără pompă de condens"],
    specs: [
      { label: "Model furnizor", value: "YD24T2" },
      { label: "Serie / gamă", value: "LCAC Duct" },
      { label: "Categorie", value: "Duct" },
      { label: "Capacitate", value: "24000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,8" },
      { label: "Eficiență încălzire", value: "A+/4,1" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yd42t1",
    slug: "yamato-yd42t1",
    name: "Yamato YD42T1 42000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 42000,
    capacityLabel: "42000 BTU",
    price: 7874,
    rating: 4.5,
    reviews: 25,
    energyClass: "A++",
    smartbillCode: "YD42T1",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Duct, categoria Duct, model YD42T1. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Presiune statică medie", "Telecomandă cu fir inclusă", "Fără pompă de condens"],
    specs: [
      { label: "Model furnizor", value: "YD42T1" },
      { label: "Serie / gamă", value: "LCAC Duct" },
      { label: "Categorie", value: "Duct" },
      { label: "Capacitate", value: "42000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yd48t1t-trifazat",
    slug: "yamato-yd48t1t-trifazat",
    name: "Yamato YD48T1T trifazat 48000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 48000,
    capacityLabel: "48000 BTU",
    price: 9007,
    rating: 4.5,
    reviews: 26,
    energyClass: "A++",
    smartbillCode: "YD48T1T-trifazat",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Duct, categoria Duct, model YD48T1T trifazat. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Presiune statică medie", "Telecomandă cu fir inclusă", "Fără pompă de condens"],
    specs: [
      { label: "Model furnizor", value: "YD48T1T trifazat" },
      { label: "Serie / gamă", value: "LCAC Duct" },
      { label: "Categorie", value: "Duct" },
      { label: "Capacitate", value: "48000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-yd55t2t-trifazat",
    slug: "yamato-yd55t2t-trifazat",
    name: "Yamato YD55T2T trifazat 55000 BTU",
    brand: "Yamato",
    category: "aer-conditionat",
    btu: 55000,
    capacityLabel: "55000 BTU",
    price: 9946,
    rating: 4.5,
    reviews: 27,
    energyClass: "A++",
    smartbillCode: "YD55T2T-trifazat",
    manageStock: true,
    stockStatus: "on-request",
    description: "Echipament Yamato LCAC Duct, categoria Duct, model YD55T2T trifazat. Preț calculat cu adaos 20% peste lista furnizorului.",
    features: ["R32", "DC Inverter", "Montaj disponibil în Arad", "Presiune statică medie", "Telecomandă cu fir inclusă", "Fără pompă de condens"],
    specs: [
      { label: "Model furnizor", value: "YD55T2T trifazat" },
      { label: "Serie / gamă", value: "LCAC Duct" },
      { label: "Categorie", value: "Duct" },
      { label: "Capacitate", value: "55000 BTU" },
      { label: "Eficiență răcire", value: "A++/6,1" },
      { label: "Eficiență încălzire", value: "A+/4,0" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "yamato-modul-wifi-lcac",
    slug: "yamato-modul-wifi-lcac-caseta-duct",
    name: "Yamato Modul Wi-Fi pentru casetă și duct",
    brand: "Yamato",
    category: "termostate-automatizari",
    capacityLabel: "Modul Wi-Fi LCAC",
    price: 76,
    rating: 4.4,
    reviews: 4,
    energyClass: "Accesoriu",
    smartbillCode: "YAMATO-MODUL-WIFI-LCAC",
    manageStock: true,
    stockStatus: "on-request",
    description: "Modul Wi-Fi Yamato pentru echipamente casetă și duct.",
    features: ["Accesoriu LCAC", "Compatibil cu casetă și duct", "Configurare la cerere"],
    specs: [
      { label: "Model", value: "Modul Wi-Fi" },
      { label: "Utilizare", value: "Module pentru casetă și duct" },
      { label: "TVA", value: "Lista furnizorului este fără TVA" },
    ],
  },
  {
    id: "ac-midea-xtreme-12000",
    slug: "midea-xtreme-save-12000-btu",
    name: "Midea Xtreme Save 12000 BTU",
    brand: "Midea",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.8,
    reviews: 24,
    isBestseller: true,
    energyClass: "A++",
    smartbillCode: "MIDEA-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Midea pentru locuințe și birouri. Prețul final se confirmă în funcție de model, stoc și montaj.",
    features: ["Tehnologie Inverter", "Funcție răcire și încălzire", "Montaj disponibil în Arad"],
    specs: [
      { label: "Capacitate", value: "12.000 BTU" },
      { label: "Montaj", value: "Disponibil la cerere" },
    ],
  },
  {
    id: "ac-fujitsu-12000",
    slug: "fujitsu-12000-btu",
    name: "Fujitsu 12000 BTU",
    brand: "Fujitsu",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.8,
    reviews: 9,
    isNew: true,
    energyClass: "A++",
    smartbillCode: "FUJITSU-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Gamă Fujitsu pentru clienți care caută fiabilitate și eficiență în climatizare.",
    features: ["Brand premium", "Soluții rezidențiale și comerciale", "Montaj profesional disponibil"],
    specs: [
      { label: "Capacitate", value: "12.000 BTU" },
    ],
  },
  {
    id: "ac-yukon-12000",
    slug: "yukon-12000-btu",
    name: "Yukon 12000 BTU",
    brand: "Yukon",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.4,
    reviews: 7,
    energyClass: "A++",
    smartbillCode: "YUKON-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Yukon pentru proiecte rezidențiale și mici spații comerciale.",
    features: ["Inverter", "Ofertă cu montaj", "Disponibilitate confirmată telefonic"],
    specs: [
      { label: "Capacitate", value: "12.000 BTU" },
    ],
  },
  {
    id: "ac-habitat-12000",
    slug: "habitat-12000-btu",
    name: "Habitat 12000 BTU",
    brand: "Habitat",
    category: "aer-conditionat",
    btu: 12000,
    capacityLabel: "12.000 BTU",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.4,
    reviews: 6,
    energyClass: "A++",
    smartbillCode: "HABITAT-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Aparat de aer condiționat Habitat, disponibil cu ofertă personalizată pentru produs și montaj.",
    features: ["Climatizare rezidențială", "Consultanță la alegere", "Montaj disponibil"],
    specs: [
      { label: "Capacitate", value: "12.000 BTU" },
    ],
  },
  {
    id: "ct-bosch-condens",
    slug: "bosch-centrala-termica-condensare",
    name: "Bosch centrală termică în condensare",
    brand: "Bosch",
    category: "centrale-termice",
    capacityLabel: "24–30 kW",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.8,
    reviews: 14,
    energyClass: "A",
    smartbillCode: "BOSCH-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Centrală termică Bosch în condensare, disponibilă cu ofertă pentru echipament, accesorii și montaj.",
    features: ["Randament ridicat", "Potrivită pentru apartamente și case", "Ofertă cu montaj și accesorii"],
    specs: [
      { label: "Putere", value: "24–30 kW, în funcție de model" },
      { label: "Tip", value: "Centrală în condensare" },
    ],
  },
  {
    id: "ct-vaillant-ecotec",
    slug: "vaillant-ecotec-centrala-termica",
    name: "Vaillant ecoTEC centrală termică",
    brand: "Vaillant",
    category: "centrale-termice",
    capacityLabel: "24–30 kW",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.9,
    reviews: 13,
    energyClass: "A",
    smartbillCode: "VAILLANT-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Centrală Vaillant pentru încălzire și apă caldă, cu ofertă personalizată pentru locuința ta.",
    features: ["Brand premium", "Compatibilă cu termostate și automatizări", "Pachet complet la cerere"],
    specs: [
      { label: "Putere", value: "În funcție de model" },
    ],
  },
  {
    id: "ct-immergas-victrix",
    slug: "immergas-victrix-centrala-termica",
    name: "Immergas Victrix centrală termică",
    brand: "Immergas",
    category: "centrale-termice",
    capacityLabel: "24–32 kW",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.7,
    reviews: 10,
    energyClass: "A",
    smartbillCode: "IMMERGAS-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Centrală termică Immergas din gama Victrix, disponibilă cu ofertă de montaj și accesorii.",
    features: ["Condensare", "Soluție pentru apartamente și case", "Accesorii disponibile"],
    specs: [
      { label: "Tip", value: "Centrală termică în condensare" },
    ],
  },
  {
    id: "ct-viessmann-vitodens",
    slug: "viessmann-vitodens-centrala-termica",
    name: "Viessmann Vitodens centrală termică",
    brand: "Viessmann",
    category: "centrale-termice",
    capacityLabel: "24–35 kW",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.9,
    reviews: 12,
    energyClass: "A",
    smartbillCode: "VIESSMANN-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Centrală Viessmann Vitodens pentru eficiență ridicată și fiabilitate pe termen lung.",
    features: ["Eficiență ridicată", "Soluții pentru case și apartamente", "Configurare la cerere"],
    specs: [
      { label: "Gamă", value: "Vitodens" },
    ],
  },
  {
    id: "pc-gree-aer-apa",
    slug: "gree-pompa-de-caldura-aer-apa",
    name: "Gree pompă de căldură aer-apă",
    brand: "Gree",
    category: "pompe-caldura",
    capacityLabel: "Monobloc / split",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.7,
    reviews: 8,
    energyClass: "A+++",
    smartbillCode: "GREE-PC-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Pompă de căldură Gree pentru încălzire, răcire și apă caldă menajeră, dimensionată pe proiect.",
    features: ["Dimensionare după necesarul termic", "Compatibilă cu puffer și boiler", "Ofertă tehnică personalizată"],
    specs: [
      { label: "Tip", value: "Aer-apă" },
    ],
  },
  {
    id: "pc-midea-aer-apa",
    slug: "midea-pompa-de-caldura-aer-apa",
    name: "Midea pompă de căldură aer-apă",
    brand: "Midea",
    category: "pompe-caldura",
    capacityLabel: "Monobloc / split",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.7,
    reviews: 7,
    energyClass: "A+++",
    smartbillCode: "MIDEA-PC-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Soluție Midea pentru încălzire eficientă cu pompă de căldură, proiectată în funcție de locuință.",
    features: ["Soluție pentru case", "Poate include puffer și boiler", "Consultanță tehnică"],
    specs: [
      { label: "Tip", value: "Aer-apă" },
    ],
  },
  {
    id: "kit-montaj-ac-3m",
    slug: "kit-montaj-aer-conditionat-3m",
    name: "Kit montaj aer condiționat 3 m",
    brand: "Generic",
    category: "accesorii-montaj-ac",
    capacityLabel: "Kit 3 m",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.6,
    reviews: 18,
    energyClass: "Accesoriu",
    smartbillCode: "KIT-AC-3M-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Kit de montaj pentru aparat de aer condiționat: traseu frigorific, izolație, furtun condens și accesorii de prindere.",
    features: ["Pentru montaj AC", "Configurabil după lungimea traseului", "Disponibil cu montaj"],
    specs: [
      { label: "Conținut", value: "Țeavă frigorifică, izolație, furtun condens, cablu și accesorii" },
    ],
  },
  {
    id: "console-ac-perete",
    slug: "console-montaj-aer-conditionat",
    name: "Console montaj aer condiționat",
    brand: "Generic",
    category: "accesorii-montaj-ac",
    capacityLabel: "Set console",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.5,
    reviews: 16,
    energyClass: "Accesoriu",
    smartbillCode: "CONSOLE-AC-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Console metalice pentru montajul unității exterioare de aer condiționat.",
    features: ["Pentru unitate exterioară", "Diverse dimensiuni", "Compatibile cu majoritatea aparatelor split"],
    specs: [
      { label: "Utilizare", value: "Montaj unitate exterioară AC" },
    ],
  },
  {
    id: "teava-ppr-fitinguri-centrale",
    slug: "teava-fitinguri-centrale-termice",
    name: "Țeavă și fitinguri pentru centrale termice",
    brand: "Generic",
    category: "teava-fitinguri",
    capacityLabel: "PPR / multistrat / cupru",
    price: 0,
    priceLabel: "Cere ofertă",
    rating: 4.6,
    reviews: 12,
    energyClass: "Instalații",
    smartbillCode: "TEAVA-FITINGURI-DE-COMPLETAT",
    manageStock: true,
    stockStatus: "on-request",
    description: "Țeavă, fitinguri, robineți și accesorii pentru instalații de încălzire, centrale termice și pompe de căldură.",
    features: ["Pentru încălzire și apă caldă", "PPR, multistrat sau cupru", "Disponibile în funcție de proiect"],
    specs: [
      { label: "Utilizare", value: "Instalații termice" },
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && (p.brand === product.brand || p.category === product.category || Boolean(product.btu && p.btu === product.btu)))
    .slice(0, count);
}
