export type Brand = 'Daikin' | 'Midea' | 'Gree' | 'LG';
export type Category = 'split' | 'multi-split' | 'caseta' | 'portabil';

export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  brand: Brand;
  category: Category;
  btu: number;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  isNew?: boolean;
  isBestseller?: boolean;
  energyClass: string;
  description: string;
  features: string[];
  specs: ProductSpec[];
}

export const BRAND_GRADIENT: Record<Brand, string> = {
  Daikin: 'from-blue-600 to-cyan-500',
  Midea:  'from-red-600 to-rose-500',
  Gree:   'from-emerald-600 to-green-500',
  LG:     'from-violet-600 to-purple-500',
};

export const CATEGORY_LABEL: Record<Category, string> = {
  'split':       'Split',
  'multi-split': 'Multi-Split',
  'caseta':      'Casetă',
  'portabil':    'Portabil',
};

export const products: Product[] = [
  /* ─── DAIKIN ─────────────────────────────────────── */
  {
    id: 'd1',
    slug: 'daikin-ftxb25c-9000-btu',
    name: 'Daikin FTXB25C',
    brand: 'Daikin',
    category: 'split',
    btu: 9000,
    price: 1899,
    originalPrice: 2199,
    rating: 4.8,
    reviews: 124,
    isBestseller: true,
    energyClass: 'A++',
    description:
      'Aparatul de aer condiționat Daikin FTXB25C combină eficiența energetică A++ cu tehnologia Inverter avansată pentru o climatizare silențioasă și economică. Ideal pentru camere de 15–25 m².',
    features: [
      'Tehnologie Inverter de ultimă generație',
      'Clasa energetică A++ (răcire) / A+ (încălzire)',
      'Nivel minim de zgomot: 21 dB(A)',
      'Filtru auto-curățare',
      'Timer programabil săptămânal',
      'Compatibil modul WiFi Daikin (opțional)',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '2,5 kW (9.000 BTU)' },
      { label: 'Capacitate încălzire', value: '3,2 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,72' },
      { label: 'COP', value: '4,00' },
      { label: 'Zgomot unitate int.', value: '21 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '15–25 m²' },
      { label: 'Dimensiuni unitate int.', value: '770 × 275 × 195 mm' },
    ],
  },
  {
    id: 'd2',
    slug: 'daikin-ftxb35c-12000-btu',
    name: 'Daikin FTXB35C',
    brand: 'Daikin',
    category: 'split',
    btu: 12000,
    price: 2299,
    rating: 4.7,
    reviews: 98,
    energyClass: 'A++',
    description:
      'Daikin FTXB35C este soluția perfectă pentru camere medii de 25–35 m². Tehnologia Inverter și refrigerantul R-32 asigură costuri reduse de funcționare și impact minim asupra mediului.',
    features: [
      'Inverter cu economie de energie până la 40%',
      'Refrigerant ecologic R-32',
      'Funcție self-clean al filtrului',
      'Pornire rapidă — temperatură dorită în 5 min',
      'Mod Econo pentru consum redus',
      'Telecomandă BRC4C',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '3,5 kW (12.000 BTU)' },
      { label: 'Capacitate încălzire', value: '4,0 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,71' },
      { label: 'COP', value: '3,98' },
      { label: 'Zgomot unitate int.', value: '22 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '25–35 m²' },
      { label: 'Dimensiuni unitate int.', value: '870 × 295 × 210 mm' },
    ],
  },
  {
    id: 'd3',
    slug: 'daikin-ftxb50c-18000-btu',
    name: 'Daikin FTXB50C',
    brand: 'Daikin',
    category: 'split',
    btu: 18000,
    price: 2999,
    rating: 4.9,
    reviews: 67,
    isNew: true,
    energyClass: 'A+',
    description:
      'Daikin FTXB50C oferă putere pentru spații mari de 35–50 m². Fluxul 3D de aer distribuie uniform temperatura în toată camera, eliminând zonele calde sau reci.',
    features: [
      'Flux aer 3D pentru distribuție uniformă',
      'Compresor twin-rotary ultra-silențios',
      'Purificare aer cu filtru argint',
      'Detectare prezență pentru economie automată',
      'Anti-mucegai pe schimbătorul de căldură',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '5,0 kW (18.000 BTU)' },
      { label: 'Capacitate încălzire', value: '5,8 kW' },
      { label: 'Clasă energetică', value: 'A+ / A+' },
      { label: 'EER', value: '3,52' },
      { label: 'COP', value: '3,80' },
      { label: 'Zgomot unitate int.', value: '26 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '35–50 m²' },
      { label: 'Dimensiuni unitate int.', value: '1.080 × 295 × 230 mm' },
    ],
  },
  {
    id: 'd4',
    slug: 'daikin-ftxb71c-24000-btu',
    name: 'Daikin FTXB71C',
    brand: 'Daikin',
    category: 'split',
    btu: 24000,
    price: 3799,
    rating: 4.6,
    reviews: 42,
    energyClass: 'A+',
    description:
      'Daikin FTXB71C este alegerea profesională pentru spații comerciale mari sau apartamente open-space de 50–70 m². Putere maximă cu zgomot minim garantat.',
    features: [
      'Putere de răcire/încălzire pentru spații mari',
      'Compresor cu piston liniar silențios',
      'Funcție anti-îngheț unitate exterioară',
      'Control de la distanță prin aplicație',
      'Program anti-bacterian automat',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '7,1 kW (24.000 BTU)' },
      { label: 'Capacitate încălzire', value: '8,0 kW' },
      { label: 'Clasă energetică', value: 'A+ / A+' },
      { label: 'EER', value: '3,44' },
      { label: 'COP', value: '3,74' },
      { label: 'Zgomot unitate int.', value: '31 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '50–70 m²' },
      { label: 'Dimensiuni unitate int.', value: '1.260 × 295 × 240 mm' },
    ],
  },
  {
    id: 'd5',
    slug: 'daikin-ftxa25cb-stylish-9000-btu',
    name: 'Daikin FTXA25CB Stylish',
    brand: 'Daikin',
    category: 'split',
    btu: 9000,
    price: 3499,
    rating: 4.9,
    reviews: 89,
    isNew: true,
    energyClass: 'A+++',
    description:
      'Daikin Stylish FTXA25CB este cel mai eficient aparat din gama Daikin cu clasă energetică A+++ și design premium ultra-plat. WiFi integrat și purificator Streamer inclus.',
    features: [
      'Clasă energetică A+++ — cea mai eficientă',
      'WiFi integrat cu app Daikin Online Controller',
      'Purificator Streamer cu ioni',
      'Design ultra-plat 189 mm grosime',
      'Senzor de calitate a aerului',
      'Corozivitate rezistentă — ideal zone costiere',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '2,5 kW (9.000 BTU)' },
      { label: 'Capacitate încălzire', value: '3,4 kW' },
      { label: 'Clasă energetică', value: 'A+++ / A++' },
      { label: 'SCOP', value: '5,10' },
      { label: 'SEER', value: '8,75' },
      { label: 'Zgomot unitate int.', value: '19 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '15–25 m²' },
      { label: 'Grosime unitate int.', value: '189 mm' },
    ],
  },

  /* ─── MIDEA ──────────────────────────────────────── */
  {
    id: 'm1',
    slug: 'midea-msaf-09n8-9000-btu',
    name: 'Midea Xtreme Save 9000',
    brand: 'Midea',
    category: 'split',
    btu: 9000,
    price: 1299,
    originalPrice: 1499,
    rating: 4.5,
    reviews: 212,
    isBestseller: true,
    energyClass: 'A++',
    description:
      'Midea Xtreme Save este liderul raport calitate-preț din gama noastră. Clasă A++ la un preț accesibil, cu toate funcțiile moderne: WiFi, auto-restart și filtrare avansată.',
    features: [
      'Raport calitate-preț imbatabil',
      'WiFi integrat — control de pe telefon',
      'Auto-restart după cădere de curent',
      'Filtru de carbon activ',
      'Funcție Turbo răcire rapidă',
      'Garanție 3 ani compresore',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '2,6 kW (9.000 BTU)' },
      { label: 'Capacitate încălzire', value: '2,8 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,65' },
      { label: 'COP', value: '3,80' },
      { label: 'Zgomot unitate int.', value: '22 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '15–25 m²' },
    ],
  },
  {
    id: 'm2',
    slug: 'midea-msaf-12n8-12000-btu',
    name: 'Midea Xtreme Save 12000',
    brand: 'Midea',
    category: 'split',
    btu: 12000,
    price: 1599,
    rating: 4.5,
    reviews: 178,
    energyClass: 'A++',
    description:
      'Midea Xtreme Save 12000 BTU este alegerea înțeleaptă pentru camere de 25–35 m². Instalare simplă, funcționare silențioasă și costuri de operare minime.',
    features: [
      'Instalare standard fără modificări',
      'Control vocal Alexa / Google Assistant',
      'Funcție auto-curatare evaporator',
      'Display LED ascuns pe unitatea interioară',
      'Mod somn pentru nopți liniștite',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '3,5 kW (12.000 BTU)' },
      { label: 'Capacitate încălzire', value: '3,7 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,62' },
      { label: 'COP', value: '3,78' },
      { label: 'Zgomot unitate int.', value: '23 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '25–35 m²' },
    ],
  },
  {
    id: 'm3',
    slug: 'midea-msaf-18n8-18000-btu',
    name: 'Midea Xtreme Save 18000',
    brand: 'Midea',
    category: 'split',
    btu: 18000,
    price: 2099,
    originalPrice: 2399,
    rating: 4.4,
    reviews: 95,
    energyClass: 'A+',
    description:
      'Midea Xtreme Save 18000 BTU — putere completă pentru livinguri și spații comerciale mici. Funcție de dezumidificare avansată și filtrare triple pentru aer curat.',
    features: [
      'Dezumidificare avansată 1,2 l/h',
      'Filtrare triple — anti-bacterian + PM2.5',
      'Funcție boost răcire în 5 minute',
      'Urmărire automată temperatură cameră',
      'Program zilnic și săptămânal',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '5,0 kW (18.000 BTU)' },
      { label: 'Capacitate încălzire', value: '5,3 kW' },
      { label: 'Clasă energetică', value: 'A+ / A+' },
      { label: 'EER', value: '3,50' },
      { label: 'COP', value: '3,72' },
      { label: 'Zgomot unitate int.', value: '27 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '35–50 m²' },
    ],
  },
  {
    id: 'm4',
    slug: 'midea-msaf-24n8-24000-btu',
    name: 'Midea Xtreme Save 24000',
    brand: 'Midea',
    category: 'split',
    btu: 24000,
    price: 2699,
    rating: 4.3,
    reviews: 54,
    energyClass: 'A+',
    description:
      'Midea Xtreme Save 24000 BTU asigură climatizarea eficientă a spațiilor de 50–70 m². Ideal pentru magazine, birouri sau apartamente cu plan deschis.',
    features: [
      'Ideal pentru spații comerciale 50–70 m²',
      'Compresor DC Inverter de înaltă eficiență',
      'Funcție de auto-diagnosticare',
      'Telecomandă inteligentă cu ecran LCD',
      'Conector BMS pentru clădiri inteligente',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '7,0 kW (24.000 BTU)' },
      { label: 'Capacitate încălzire', value: '7,3 kW' },
      { label: 'Clasă energetică', value: 'A+ / A' },
      { label: 'EER', value: '3,38' },
      { label: 'COP', value: '3,60' },
      { label: 'Zgomot unitate int.', value: '34 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '50–70 m²' },
    ],
  },
  {
    id: 'm5',
    slug: 'midea-msuaf-18-all-seasons',
    name: 'Midea All Seasons 18000',
    brand: 'Midea',
    category: 'split',
    btu: 18000,
    price: 2399,
    isNew: true,
    rating: 4.7,
    reviews: 31,
    energyClass: 'A++',
    description:
      'Midea All Seasons funcționează eficient până la -25°C exterior. Soluția ideală pentru iernile românești aspre — încălzire garantată indiferent de temperatura exterioară.',
    features: [
      'Funcționare la -25°C temperatură exterioară',
      'Pornire rapidă la temperaturi scăzute',
      'Dezghețare inteligentă a unității exterioare',
      'Mode Jet Cool — 18°C în 3 minute',
      'Certificare H&T pentru climat extrem',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '5,2 kW (18.000 BTU)' },
      { label: 'Capacitate încălzire', value: '6,0 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'Temp. ext. min. funcționare', value: '-25°C' },
      { label: 'EER', value: '3,68' },
      { label: 'COP', value: '3,90' },
      { label: 'Zgomot unitate int.', value: '25 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '35–50 m²' },
    ],
  },

  /* ─── GREE ──────────────────────────────────────── */
  {
    id: 'g1',
    slug: 'gree-gwh09acc-9000-btu',
    name: 'Gree Bora A4 9000',
    brand: 'Gree',
    category: 'split',
    btu: 9000,
    price: 1199,
    originalPrice: 1399,
    rating: 4.4,
    reviews: 187,
    isBestseller: true,
    energyClass: 'A++',
    description:
      'Gree Bora A4 este cel mai vândut aparat de climatizare economic din România. Fiabilitate dovedită, piese de schimb disponibile, service rapid în toată țara.',
    features: [
      'Cel mai bun preț din categorie',
      'Filtru auto-curățare cu uscare UV',
      'Funcție de auto-repornire',
      'Mod ventilare independentă',
      'Telecomandă cu ecran retroiluminat',
      'Service național — 250+ puncte autorizate',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '2,6 kW (9.000 BTU)' },
      { label: 'Capacitate încălzire', value: '3,2 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,60' },
      { label: 'COP', value: '3,75' },
      { label: 'Zgomot unitate int.', value: '22 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '15–25 m²' },
    ],
  },
  {
    id: 'g2',
    slug: 'gree-gwh12acc-12000-btu',
    name: 'Gree Bora A4 12000',
    brand: 'Gree',
    category: 'split',
    btu: 12000,
    price: 1499,
    rating: 4.4,
    reviews: 142,
    energyClass: 'A++',
    description:
      'Gree Bora A4 12000 BTU — fiabilitate japoneză la preț accesibil. Compresorul fabricat în propria fabrică Gree asigură durabilitate și eficiență pe termen lung.',
    features: [
      'Compresor propriu Gree — durabilitate dovedită',
      'Mod de dezumidificare 0,9 l/h',
      'Funcție anti-mucegai automată',
      'Afișaj ascuns cu LED discret',
      'Modul WiFi U-MATCH opțional',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '3,5 kW (12.000 BTU)' },
      { label: 'Capacitate încălzire', value: '3,8 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,58' },
      { label: 'COP', value: '3,74' },
      { label: 'Zgomot unitate int.', value: '24 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '25–35 m²' },
    ],
  },
  {
    id: 'g3',
    slug: 'gree-gwh18acc-18000-btu',
    name: 'Gree Bora A4 18000',
    brand: 'Gree',
    category: 'split',
    btu: 18000,
    price: 1999,
    rating: 4.3,
    reviews: 76,
    energyClass: 'A+',
    description:
      'Gree Bora A4 18000 BTU este soluția economică pentru camerele mari. Putere suficientă pentru 35–50 m² cu consum energetic minim.',
    features: [
      'Putere pentru camere 35–50 m²',
      'Schimbător de căldură din aluminiu epoxidic',
      'Funcție follow-me cu senzor telecomandă',
      'Mod economie automată',
      'Filtru antibacterian inclus',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '5,2 kW (18.000 BTU)' },
      { label: 'Capacitate încălzire', value: '5,5 kW' },
      { label: 'Clasă energetică', value: 'A+ / A+' },
      { label: 'EER', value: '3,44' },
      { label: 'COP', value: '3,68' },
      { label: 'Zgomot unitate int.', value: '28 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '35–50 m²' },
    ],
  },
  {
    id: 'g4',
    slug: 'gree-gwh24acc-24000-btu',
    name: 'Gree Bora A4 24000',
    brand: 'Gree',
    category: 'split',
    btu: 24000,
    price: 2499,
    rating: 4.2,
    reviews: 38,
    energyClass: 'A+',
    description:
      'Gree Bora A4 24000 BTU — cea mai economică soluție pentru spații mari de 50–70 m². Alegerea inteligentă pentru proprietari care vor confort fără să supradimensioneze bugetul.',
    features: [
      'Raport putere-preț imbatabil în categorie',
      'Compresor twin-rotary robust',
      'Protecție complet la supratensiune',
      'Funcție de blocare copii',
      'Timer zilnic 24h',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '7,0 kW (24.000 BTU)' },
      { label: 'Capacitate încălzire', value: '7,5 kW' },
      { label: 'Clasă energetică', value: 'A+ / A' },
      { label: 'EER', value: '3,33' },
      { label: 'COP', value: '3,58' },
      { label: 'Zgomot unitate int.', value: '35 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '50–70 m²' },
    ],
  },
  {
    id: 'g5',
    slug: 'gree-gwh12yd-comfort-x-12000-btu',
    name: 'Gree Comfort X 12000',
    brand: 'Gree',
    category: 'split',
    btu: 12000,
    price: 2199,
    isNew: true,
    rating: 4.7,
    reviews: 29,
    energyClass: 'A+++',
    description:
      'Gree Comfort X reprezintă vârful gamei Gree — clasă A+++ cu WiFi integrat și purificator de aer cu ioni de argint. Cel mai avansat aparat Gree disponibil în România.',
    features: [
      'Clasă energetică A+++ — top eficiență',
      'WiFi și control vocal Google/Alexa integrat',
      'Purificator Gree Fresh Air — ioni Ag+',
      'Afișaj LED 10.000 culori (Comfort X)',
      'Senzor corp uman pentru adaptare automată',
      'Auto-curatare completă în 30 minute',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '3,5 kW (12.000 BTU)' },
      { label: 'Capacitate încălzire', value: '4,2 kW' },
      { label: 'Clasă energetică', value: 'A+++ / A++' },
      { label: 'SEER', value: '8,50' },
      { label: 'SCOP', value: '5,20' },
      { label: 'Zgomot unitate int.', value: '19 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '25–35 m²' },
    ],
  },

  /* ─── LG ─────────────────────────────────────────── */
  {
    id: 'l1',
    slug: 'lg-s09eq-9000-btu',
    name: 'LG DUALCOOL S09EQ',
    brand: 'LG',
    category: 'split',
    btu: 9000,
    price: 1699,
    originalPrice: 1999,
    rating: 4.7,
    reviews: 156,
    isBestseller: true,
    energyClass: 'A++',
    description:
      'LG DUALCOOL S09EQ cu compresor Dual Inverter asigură un nivel de zgomot de numai 19 dB(A) — silențios ca o bibliotecă. Funcționare stabilă și rapidă la orice temperatură exterioară.',
    features: [
      'Compresor Dual Inverter — 70% mai silențios',
      'Nivelul minim de zgomot 19 dB(A)',
      'ThinQ WiFi — control de pe telefon',
      'Auto Cleaning — auto-curățare evaporator',
      'Plasmaster Ionizer+ — purificare aer',
      'Dual Protection Filter antibacterian',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '2,5 kW (9.000 BTU)' },
      { label: 'Capacitate încălzire', value: '3,2 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,78' },
      { label: 'COP', value: '4,10' },
      { label: 'Zgomot unitate int.', value: '19 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '15–25 m²' },
    ],
  },
  {
    id: 'l2',
    slug: 'lg-s12eq-12000-btu',
    name: 'LG DUALCOOL S12EQ',
    brand: 'LG',
    category: 'split',
    btu: 12000,
    price: 2099,
    rating: 4.7,
    reviews: 118,
    energyClass: 'A++',
    description:
      'LG DUALCOOL S12EQ combină puterea de 12.000 BTU cu cea mai avansată tehnologie de purificare a aerului din industrie. ThinQ AI adaptează temperatura în funcție de obiceiurile tale.',
    features: [
      'ThinQ AI — învatță preferințele tale',
      'Plasmaster Ionizer+ 360° purificare',
      'Răcire de urgență Jet Cool',
      'SmartDiagnosis prin aplicație',
      'Auto Cleaning cu uscare automată',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '3,5 kW (12.000 BTU)' },
      { label: 'Capacitate încălzire', value: '4,0 kW' },
      { label: 'Clasă energetică', value: 'A++ / A+' },
      { label: 'EER', value: '3,74' },
      { label: 'COP', value: '4,05' },
      { label: 'Zgomot unitate int.', value: '21 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '25–35 m²' },
    ],
  },
  {
    id: 'l3',
    slug: 'lg-s18eq-18000-btu',
    name: 'LG DUALCOOL S18EQ',
    brand: 'LG',
    category: 'split',
    btu: 18000,
    price: 2699,
    rating: 4.6,
    reviews: 72,
    energyClass: 'A+',
    description:
      'LG DUALCOOL S18EQ aduce tehnologia LG premium pentru spații mari. Distribuitorul de aer 4-căi acoperă uniform toată camera, fără zone reci sau calde.',
    features: [
      'Distribuție aer 4 căi pentru acoperire maximă',
      'Anti-virus filtru cu ioni de argint și zinc',
      'Detectare scurgere de refrigerant',
      'Mod Step Control pentru consum optim',
      'Ecran LED tactil pe unitatea interioară',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '5,3 kW (18.000 BTU)' },
      { label: 'Capacitate încălzire', value: '5,8 kW' },
      { label: 'Clasă energetică', value: 'A+ / A+' },
      { label: 'EER', value: '3,55' },
      { label: 'COP', value: '3,84' },
      { label: 'Zgomot unitate int.', value: '26 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '35–50 m²' },
    ],
  },
  {
    id: 'l4',
    slug: 'lg-s24eq-24000-btu',
    name: 'LG DUALCOOL S24EQ',
    brand: 'LG',
    category: 'split',
    btu: 24000,
    price: 3299,
    rating: 4.5,
    reviews: 44,
    energyClass: 'A+',
    description:
      'LG DUALCOOL S24EQ — puterea maximă din gama residențial LG pentru spații de 50–70 m². Compresorul Dual Inverter asigură răcire/încălzire rapidă cu consum minim.',
    features: [
      'Compresor Dual Inverter pentru putere maximă',
      'Funcție Booster pentru răcire fulger',
      '10 ani garanție compresor',
      'Protecție împotriva coroziunii Blue Fin',
      'Conectivitate Google Home / Amazon Alexa',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '7,0 kW (24.000 BTU)' },
      { label: 'Capacitate încălzire', value: '8,0 kW' },
      { label: 'Clasă energetică', value: 'A+ / A+' },
      { label: 'EER', value: '3,50' },
      { label: 'COP', value: '3,78' },
      { label: 'Zgomot unitate int.', value: '32 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '50–70 m²' },
    ],
  },
  {
    id: 'l5',
    slug: 'lg-ac09bq-artcool-9000-btu',
    name: 'LG ArtCool AC09BQ',
    brand: 'LG',
    category: 'split',
    btu: 9000,
    price: 3399,
    isNew: true,
    rating: 4.9,
    reviews: 63,
    energyClass: 'A+++',
    description:
      'LG ArtCool este cel mai stilat aparat de climatizare de pe piață — design minimalist cu oglindă integrată care se armonizează cu orice interior modern. A+++ și WiFi inclus.',
    features: [
      'Design premium cu panou-oglindă',
      'Clasă energetică A+++ — eficiență maximă',
      'ThinQ WiFi și control vocal AI',
      'Plasmaster Ionizer+ — purificare 360°',
      'Cel mai silențios LG: 19 dB(A)',
      'Auto Cleaning cu uscare UV',
    ],
    specs: [
      { label: 'Capacitate răcire', value: '2,5 kW (9.000 BTU)' },
      { label: 'Capacitate încălzire', value: '3,5 kW' },
      { label: 'Clasă energetică', value: 'A+++ / A++' },
      { label: 'SEER', value: '8,80' },
      { label: 'SCOP', value: '5,10' },
      { label: 'Zgomot unitate int.', value: '19 dB(A)' },
      { label: 'Refrigerant', value: 'R-32' },
      { label: 'Suprafață recomandată', value: '15–25 m²' },
    ],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && (p.brand === product.brand || p.btu === product.btu))
    .slice(0, count);
}
