-- Online withdrawal function required by OUG 34/2014 art. 11^1 (applicable 19.06.2026).
-- Phase 1 is backward compatible with the legacy public form: it extends the table and
-- relaxes legacy fields that are not required by art. 11^1. Direct client insert grants
-- are intentionally removed only after the server-side flow is live.

alter table public.retrageri
  alter column adresa drop not null,
  alter column telefon drop not null,
  alter column produs drop not null,
  alter column cantitate drop not null,
  alter column pret drop not null,
  alter column data_comanda drop not null,
  alter column data_primire drop not null,
  alter column motiv drop not null,
  alter column metoda_rambursare drop not null;

alter table public.retrageri
  add column if not exists client_submission_id uuid,
  add column if not exists declaratie jsonb,
  add column if not exists confirmation_email text,
  add column if not exists confirmata_la timestamptz,
  add column if not exists confirmation_email_sent_at timestamptz;

create unique index if not exists retrageri_client_submission_id_unique_idx
  on public.retrageri (client_submission_id)
  where client_submission_id is not null;

alter table public.retrageri
  drop constraint if exists retrageri_online_submission_requires_data;

alter table public.retrageri
  add constraint retrageri_online_submission_requires_data
  check (
    client_submission_id is null
    or (
      declaratie is not null
      and length(btrim(coalesce(confirmation_email, ''))) > 0
      and confirmata_la is not null
    )
  );

comment on column public.retrageri.client_submission_id is
  'Idempotency UUID generated by the online withdrawal UI; unique for retry-safe submissions.';
comment on column public.retrageri.declaratie is
  'Immutable snapshot of the consumer online withdrawal declaration.';
comment on column public.retrageri.confirmation_email is
  'Electronic destination chosen/confirmed by the consumer for the durable-medium acknowledgment.';
comment on column public.retrageri.confirmata_la is
  'Server timestamp when the consumer activated the explicit confirmation function.';
comment on column public.retrageri.confirmation_email_sent_at is
  'Timestamp when the durable-medium withdrawal acknowledgment email was accepted by the email provider.';
